# Generated by Django 4.2.2 on 2023-06-26 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_app', '0002_rename_development_studio_developmentstudio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='short_description',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
